### ISSUE TITLE
Rejected claims bug when the user is authenticated.

### ISSUE THREAD

**Issue by ramiroluz** [interlegis/interlegis.portalmodelo.ombudsman#18]
The email field is not being rendered when the claim is rejected.

URL: /var/interlegis/portalmodelo/src/interlegis.portalmodelo.ombudsman/src/interlegis/portalmodelo/ombudsman/browser/templates/claim_view.pt
Line 65, Column 10
Expression: <PathExpr standard:u'view/w/email/label'>

**Comment by ramiroluz** [comment]
It appears that the problem is with the permission in [claim.py](https://github.com/interlegis/interlegis.portalmodelo.ombudsman/blob/master/src/interlegis/portalmodelo/ombudsman/interfaces/claim.py#L53) interface.

Using AddPortalContent instead of ModifyPortalContent seems to work.

But I don't know if there is any side effect of it.

**Comment by hvelarde** [comment]
which roles should be able to view that field?

**Comment by ramiroluz** [comment]
As far as I know, to view this field the user must be authenticated.

I think it would be better to have a specific role assigned to some users, like:
- ViewClaimPersonalInfo
- ModifyClaim
- AddClaimResponse
- ...

And so on.
